#!/bin/bash

# Setup script for cross-platform secrets management
# This script copies secrets.properties to all required locations

echo "🔧 Setting up secrets for all platforms..."

# Check if secrets.properties exists
if [ ! -f "secrets.properties" ]; then
    echo "❌ secrets.properties not found in project root"
    echo "📝 Please copy secrets.properties.template to secrets.properties and fill in your values"
    exit 1
fi

echo "✅ Found secrets.properties in project root"

# Create Android assets directory if it doesn't exist
ANDROID_ASSETS_DIR="composeApp/src/androidMain/assets"
if [ ! -d "$ANDROID_ASSETS_DIR" ]; then
    echo "📁 Creating Android assets directory: $ANDROID_ASSETS_DIR"
    mkdir -p "$ANDROID_ASSETS_DIR"
fi

# Copy secrets to Android assets
echo "📋 Copying secrets.properties to Android assets..."
cp secrets.properties "$ANDROID_ASSETS_DIR/"
echo "✅ Android secrets configured"

# Update Web config.json with values from secrets.properties
echo "🌐 Updating Web config.json..."
WEB_CONFIG="composeApp/src/wasmJsMain/resources/config.json"

# Function to read property from secrets.properties
get_property() {
    local key=$1
    local value=$(grep "^$key=" secrets.properties | cut -d'=' -f2- | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
    echo "$value"
}

# Read values from secrets.properties
ENVIRONMENT=$(get_property "environment")
DEV_SUPABASE_URL=$(get_property "dev.supabase.url")
DEV_SUPABASE_KEY=$(get_property "dev.supabase.key")
DEV_SERVER_URL=$(get_property "dev.server.url")
PROD_SUPABASE_URL=$(get_property "prod.supabase.url")
PROD_SUPABASE_KEY=$(get_property "prod.supabase.key")
PROD_SERVER_URL=$(get_property "prod.server.url")

# Create config.json with actual values
cat > "$WEB_CONFIG" << EOF
{
  "environment": "${ENVIRONMENT:-dev}",
  "dev.supabase.url": "${DEV_SUPABASE_URL:-}",
  "dev.supabase.key": "${DEV_SUPABASE_KEY:-}",
  "dev.server.url": "${DEV_SERVER_URL:-http://localhost:4000}",
  "prod.supabase.url": "${PROD_SUPABASE_URL:-}",
  "prod.supabase.key": "${PROD_SUPABASE_KEY:-}",
  "prod.server.url": "${PROD_SERVER_URL:-}"
}
EOF

echo "✅ Web config.json updated"

# Setup iOS secrets
echo "🍎 Setting up iOS secrets..."
IOS_RESOURCES_DIR="iosApp/iosApp"
if [ ! -d "$IOS_RESOURCES_DIR" ]; then
    echo "⚠️ iOS app directory not found: $IOS_RESOURCES_DIR"
    echo "   Skipping iOS setup..."
else
    # Copy secrets.properties to iOS app bundle (for runtime loading)
    echo "📋 Copying secrets.properties to iOS app bundle..."
    cp secrets.properties "$IOS_RESOURCES_DIR/secrets.properties"
    
    # Create iOS JSON configuration file (more reliable for bundle inclusion)
    echo "📋 Creating iOS config.json file..."
    cat > "$IOS_RESOURCES_DIR/config.json" << EOF
{
  "environment": "${ENVIRONMENT:-dev}",
  "dev.supabase.url": "${DEV_SUPABASE_URL:-}",
  "dev.supabase.key": "${DEV_SUPABASE_KEY:-}",
  "dev.server.url": "${DEV_SERVER_URL:-http://localhost:4000}",
  "prod.supabase.url": "${PROD_SUPABASE_URL:-}",
  "prod.supabase.key": "${PROD_SUPABASE_KEY:-}",
  "prod.server.url": "${PROD_SERVER_URL:-}"
}
EOF
    
    # Also create a Swift configuration file for easier bundle inclusion
    echo "📋 Creating iOS Config.swift file..."
    cat > "$IOS_RESOURCES_DIR/Config.swift" << EOF
// Auto-generated configuration file
// This file is generated by setup-secrets.sh and should not be edited manually

import Foundation

struct AppConfig {
    static let environment = "${ENVIRONMENT:-dev}"
    static let devSupabaseUrl = "${DEV_SUPABASE_URL:-}"
    static let devSupabaseKey = "${DEV_SUPABASE_KEY:-}"
    static let devServerUrl = "${DEV_SERVER_URL:-http://localhost:4000}"
    static let prodSupabaseUrl = "${PROD_SUPABASE_URL:-}"
    static let prodSupabaseKey = "${PROD_SUPABASE_KEY:-}"
    static let prodServerUrl = "${PROD_SERVER_URL:-}"
}
EOF

    # Create iOS Kotlin embedded config file (this will always work without bundle resources)
    echo "📋 Creating iOS Kotlin embedded config file..."
    IOS_KOTLIN_CONFIG="composeApp/src/iosMain/kotlin/org/aryamahasangh/config/IOSEmbeddedConfig.kt"
    mkdir -p "$(dirname "$IOS_KOTLIN_CONFIG")"
    cat > "$IOS_KOTLIN_CONFIG" << EOF
// Auto-generated configuration file
// This file is generated by setup-secrets.sh and should not be edited manually

package org.aryamahasangh.config

/**
 * Embedded configuration for iOS
 * These values are compiled into the app and don't require bundle resources
 */
object IOSEmbeddedConfig {
    const val ENVIRONMENT = "${ENVIRONMENT:-dev}"
    const val DEV_SUPABASE_URL = "${DEV_SUPABASE_URL:-}"
    const val DEV_SUPABASE_KEY = "${DEV_SUPABASE_KEY:-}"
    const val DEV_SERVER_URL = "${DEV_SERVER_URL:-http://localhost:4000}"
    const val PROD_SUPABASE_URL = "${PROD_SUPABASE_URL:-}"
    const val PROD_SUPABASE_KEY = "${PROD_SUPABASE_KEY:-}"
    const val PROD_SERVER_URL = "${PROD_SERVER_URL:-}"
    
    fun getConfigMap(): Map<String, String> = mapOf(
        "environment" to ENVIRONMENT,
        "dev.supabase.url" to DEV_SUPABASE_URL,
        "dev.supabase.key" to DEV_SUPABASE_KEY,
        "dev.server.url" to DEV_SERVER_URL,
        "prod.supabase.url" to PROD_SUPABASE_URL,
        "prod.supabase.key" to PROD_SUPABASE_KEY,
        "prod.server.url" to PROD_SERVER_URL
    )
}
EOF
    
    echo "✅ iOS secrets configured (properties + JSON + Swift config + Kotlin embedded)"
fi

echo ""
echo "🎉 Secrets setup complete for all platforms!"
echo ""
echo "📋 Summary:"
echo "   ✅ Desktop: Uses secrets.properties from project root"
echo "   ✅ Android: Uses secrets.properties from assets/"
echo "   ✅ Web: Uses config.json with values from secrets.properties"
echo "   ✅ iOS: Uses secrets.properties from app bundle + Swift Config.swift"
echo ""
echo "🚀 You can now run your app on any platform with proper secrets loading!"