// Auto-generated configuration file
// This file is generated by setup-secrets.sh and should not be edited manually

package com.aryamahasangh.config

/**
 * Embedded configuration for iOS
 * These values are compiled into the app and don't require bundle resources
 */
object IOSEmbeddedConfig {
  const val ENVIRONMENT = "dev"
  const val DEV_SUPABASE_URL = "https://ftnwwiwmljcwzpsawdmf.supabase.co"
  const val DEV_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0bnd3aXdtbGpjd3pwc2F3ZG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MzE4OTMsImV4cCI6MjA1MDUwNzg5M30.cY4A4ZxqHA_1VRC-k6URVAHHkweHTR8FEYEzHYiu19A"
  const val DEV_SERVER_URL = "http://localhost:4000"
  const val PROD_SUPABASE_URL = ""
  const val PROD_SUPABASE_KEY = ""
  const val PROD_SERVER_URL = "https://your-production-server.com"

  fun getConfigMap(): Map<String, String> =
    mapOf(
      "environment" to ENVIRONMENT,
      "dev.supabase.url" to DEV_SUPABASE_URL,
      "dev.supabase.key" to DEV_SUPABASE_KEY,
      "dev.server.url" to DEV_SERVER_URL,
      "prod.supabase.url" to PROD_SUPABASE_URL,
      "prod.supabase.key" to PROD_SUPABASE_KEY,
      "prod.server.url" to PROD_SERVER_URL
    )
}
