package com.aryamahasangh.features.gurukul.domain.models

import kotlinx.datetime.Instant

// Domain model for Courses loaded via LoadAllCoursesQuery
// Only use camelCase fields as generated by Apollo
// Avoid nullables except where truly optional from API/schema
// Add custom serialization annotations if needed for multiplatform

data class Course(
  val id: String,
  val name: String,
  val startDatetime: Instant,
  val endDatetime: Instant,
  val allowedGender: String, // GenderFilter
  val address: Address?,
  val capacity: Int?,
)

// Address nested domain model, matches query
data class Address(
  val district: String?,
  val state: String?,
  val latitude: Double?,
  val longitude: Double?,
)
